import React from "react";

const PrivacyPolicy = () => (
  <div>
    <h1>Privacy Policy for BirthdayAI</h1>
    <p>Last updated: 06/14/2023</p>

    <p>
      At BirthdayAI, we respect your privacy and are committed to protecting it
      through this Privacy Policy. This policy applies to the BirthdayAI mobile
      application (the "App"), and it governs data collection, processing and
      usage in compliance with the General Data Protection Regulation (GDPR).
    </p>

    <h2>Data Collection</h2>
    <p>While using BirthdayAI, we ask for the following information:</p>
    <ul>
      <li>
        Phone Number: We collect your phone number for login purposes and to
        send you personalized reminders.
      </li>
      <li>
        Contacts: With your permission, we access your contacts to make it
        easier for you to add them to the App.
      </li>
      <li>
        Calendar: We access your calendar, with your permission, to set
        reminders for birthdays, anniversaries, holidays, and more.
      </li>
    </ul>

    <h2>Data Usage</h2>
    <p>
      The information we collect is used solely to improve your user experience
      and ensure the functionality of BirthdayAI. We use your phone number to
      log you into the App and to send you personalized reminders. Access to
      your contacts and calendar helps simplify the process of setting reminders
      and ensuring you never miss an important occasion.
    </p>

    <h2>Data Protection</h2>
    <p>
      Your data is stored securely. We do not store any sensitive data apart
      from your phone number and the user ID generated by Firebase. We do not
      share your data with any third parties, and it's used exclusively for the
      purpose of providing and improving the services of BirthdayAI.
    </p>

    <h2>Changes to Privacy Policy</h2>
    <p>
      We may update our Privacy Policy from time to time. We will notify you of
      any changes by posting the new Privacy Policy on this page.
    </p>

    <h2>Contact Us</h2>
    <p>
      If you have any questions or suggestions about our Privacy Policy, do not
      hesitate to contact us.
    </p>
  </div>
);

export default PrivacyPolicy;
